/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.douyu.lib.http;

import android.util.Log;
import android.content.Context;

public class JniMakeUrl {
    private static final String a = "ZC_JAVA_N_JniLive";
    
    private native String native_authcodeDecode(Context p1, String p2, String p3);
    
    
    private native String native_authcodeEncode(Context p1, String p2, String p3);
    
    
    private native String native_getCodeE(Context p1);
    
    
    private native String native_getSDKE(Context p1);
    
    
    private native String[] native_getVideoAuth(Context p1, int p2, long p3, String p4);
    
    
    private native String native_makeUrl(Context p1, String p2, String[] p3, String[] p4, String[] p5, String[] p6, int p7, int p8);
    
    
    private native String native_newmakeUrl(Context p1, String p2, String[] p3, String[] p4, String[] p5, String[] p6, int p7, int p8);
    
    
    private native String native_sdk_version();
    
    private static b = 0x0;
    private static = 0x0;
    
    private static void b() {
        // :( Parsing error. Please contact me.
    }
    
    public JniMakeUrl() {
        if(b) {
            Log.i("ZC_JAVA_N_JniLive", "[JniMakeUrl]");
        }
        b();
    }
    
    public String a() {
        return native_sdk_version();
    }
    
    public String a(Context p1) {
        return native_getCodeE(p1);
    }
    
    public String b(Context p1) {
        return native_getSDKE(p1);
    }
    
    public String a(Context p1, String p2, String[] p3, String[] p4, String[] p5, String[] p6, int p7, int p8) {
        return native_makeUrl(p1, p2, p3, p4, p5, p6, p7, p8);
    }
    
    public String b(Context p1, String p2, String[] p3, String[] p4, String[] p5, String[] p6, int p7, int p8) {
        return native_newmakeUrl(p1, p2, p3, p4, p5, p6, p7, p8);
    }
    
    public String a(Context p1, String p2, String p3) {
        return native_authcodeDecode(p1, p2, p3);
    }
    
    public String b(Context p1, String p2, String p3) {
        return native_authcodeEncode(p1, p2, p3);
    }
    
    public String[] a(Context p1, int p2, long p3, String p4) {
        return native_getVideoAuth(p1, p2, p3, p3, p4);
    }
}
